[package]
name = "infinityx-os-2"
version = "1.0.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
x86_64 = "0.14"
bit_field = "0.10"

[features]
default = []

[[bin]]
name = "os"
path = "src/main.rs"
test = false
doctest = false
bench = false

[profile.release]
panic = "abort"
lto = "off"