[package]
name = "infinityx-os-2"
version = "1.0.0"
edition = "2021"

[dependencies]
bootloader = "0.9"

[[bin]]
name = "os"
path = "src/main.rs"
test = false
doctest = false
bench = false

[profile.release]
panic = "abort"
lto = true