name: Rust Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        source "$HOME/.cargo/env"
    
    - name: Setup Build Environment
      run: |
        rustup component add rust-src llvm-tools-preview
        rustup target add x86_64-unknown-none
        cargo install bootimage --verbose
      
    - name: Create Bootimage
      run: cargo bootimage --release --verbose
      
    - name: Upload Bootable Image
      uses: actions/upload-artifact@v4
      with:
        name: bootimage-os
        path: target/x86_64-infinityx/release/bootimage-os.bin
        compression-level: 9
        retention-days: 5
