name: Rust Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Executable Script
      run: chmod +x scripts/install.sh
    
    - name: Install Dependencies
      run: ./scripts/install.sh
      
    - name: Create Bootimage
      run: cargo bootimage --release --verbose
      
    - name: Upload Bootable Image
      uses: actions/upload-artifact@v4
      with:
        name: os-image
        path: target/x86_64-infinityx/release/bootimage-os.bin
        compression-level: 9
        retention-days: 5
        
    - name: Clean
      run: cargo clean
